### ISSUE TITLE
Inhoud van MD

### ISSUE THREAD

**Issue by pascalculator** [adriaanvermeire/web-backend-oplossingen#1]
Hallo Adriaan,

niet slecht dat je tussen de ribbetjes en de lessen nog tijd hebt gevonden om dit snel op te lossen :+1:  In de het voorbeeld motivatie.md bestand stond wel nog een extra opdrachtje (niet dat het per se nodig was om de inhoud van dat bestand te bekijken om een vinkje voor je naam te krijgen). Ik had graag gehad dat je dit ook had opgenomen in jouw motivatie.md

Als je niet zeker weet hoe het moet, kan je altijd eens naar de repo van Thomas Verhelst kijken, maar liefst eerst even zonder hulp proberen uit te vissen.

Knap!

**Comment by adriaanvermeire** [comment]
Ik had dit bericht nog niet gezien, maar heb het ondertussen ook al opgelost en ingevuld!

**Comment by pascalculator** [comment]
Nice. Bedankt voor de feedback ook! Btw, die "200 OK" maakte niet uit denk ik, gewoon een motivatie.md hebben in de juiste mappenstructuur was al voldoende. Tot volgende periode ;)
